name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build the Docker image
    - uses: actions/checkout@v3
      run: docker buildx build --platform linux/arm/v8 -f ./Dockerfile -t sebastiansu/ubuntu_arm64v8_buildenv .
